### PR TITLE
Add more binary patterns (incomplete)

### PR DESCRIPTION
**Pull request by rengolin**
This doesn't seem to be working, as the only pattern that gets matches is the last one I create (here, `Div`).

I'm not sure I'm doing it right, either. There's a `any_of` pattern, but the usage seems very different.

I think we can match all binary element-wise in the same place.

### CODE REVIEW

**Comment by adam-smnk** [comment]
I think you have to gather nodes you wanna lower before calling `ngraph_to_mlir` but no clue about exact details.

**Comment by adam-smnk** [comment]
Ohhh I see, it could still work to generate separate fragments.
I found this passage in `matcher-pass.rst`:
> Only one matcher can be registered for a single MatcherPass class.

I managed to match multiple ops by templating the base lowering class and registering multiple separate ~~matchers~~ passes.
I think long term, we want to traverse the graph and find larger subgraphs for offloading.

**Comment by rengolin** [comment]
> I think long term, we want to traverse the graph and find larger subgraphs for offloading.

Right, it will be less obvious, I was just testing multiple matching. I guess we can begin matching more complex patterns first as separate classes, then. Should be easier for now, but not sure how generic they can be (ie. matching variations of a pattern, ex. broadcast).

**Comment by slyalin** [comment]
I'm rewriting this part to capture a single partition with multiple ops, so, this intermediate change is not likely needed now.

**Pull request closed without merging**
